fixing error
Failed building JavaScript bundle.
SyntaxError: C:\Users\gabri\OneDrive\Documents\CSE120\CSE120\ProjectCombine\navigation\DrawerNavigator.tsx: Identifier 'connect' has already been declared (31:9)

  29 | import firebase from "firebase";
  30 |
> 31 | import { connect } from "react-redux";
     |          ^
  32 |
  33 | require("firebase/firestore");
  34 |